Specify power port variations
monome/docs pull request #361
Opened 2022-06-13 21:02 UTC by zjb-s

Not sure on the phrasing here, I'd welcome an edit. Best I could think of at the moment :)

2022-06-13 21:05 UTC, zjb-s commented
ah,we might also want to add a note that pi 4's want 3A: 

"The Pi4 has a USB-C power port and 3A / 5.1V is recommended."

2022-06-14 13:00 UTC, dndrks requested changes
rad! tyty -- lmk if these notes align!

2022-06-14 13:00 UTC, dndrks commented on norns/shield.md
> +- locate the port on the Pi labeled `POWER` or `PWR IN`. this will be micro-USB or USB-C, depending on your Pi edition.
rad, thank you for the eyes!

- re: `POWER`/`PWR IN`, i think fates is the only iteration of shield with two potential power ports -- most likely folks won't see these indicators (especially with our stock case), so i think it's best to leave this out to avoid confusion
- re: micro-USB or USB-C, it might be best to specify which supply goes with which Pi -- if the reader is at this point and there's still ambiguity, then they're likely going to need a direct association

does this rephrasing feel good to you?
> - locate the micro-USB (Pi 3) or USB-C (Pi 4) port on the back of the unit -- this is the power input

2022-06-14 13:00 UTC, dndrks commented on norns/shield.md
> +- attach a high quality Raspberry Pi power supply that provides at least 2A at 5V to this port.
this might be a good place to link back to the `requirements` section:

> - attach a high quality Raspberry Pi  power supply to the power input. see the [requirements section](/docs/shield/#requirements) further up this page for recommended specs.

2022-06-14 21:19 UTC, zjb-s commented on norns/shield.md
> +- locate the port on the Pi labeled `POWER` or `PWR IN`. this will be micro-USB or USB-C, depending on your Pi edition.
POWER vs PWR IN is just the labeling on the PCB with pi 4 and pi 3 respectively, so it's not a matter of two concurrent power ports. but you're dead on about the stock case - i didn't think of that!

That rephrasing looks great to me. Thanks Dan!

2022-12-15 15:58 UTC, dndrks commented
added via https://github.com/monome/docs/commit/f701650ae75d751befbb5a3b5d0da55c61fd8a4a, thank you for proposing these changes @zjb-s !!

2022-12-15 15:58 UTC, closed without merging